"""Audit and clean up W&B artifact storage for novel-harness.

Dry-run by default — shows what would be kept vs deleted with sizes.
Pass --delete to actually purge.

Usage:
  set -a; source .env; set +a
  python3 scripts/cleanup-wandb-storage.py          # dry run
  python3 scripts/cleanup-wandb-storage.py --delete  # actually delete
"""

import sys
import wandb

ENTITY = "andre14618-"
PROJECT = "novel-harness"

# ── Only keep what W&B Inference needs to SERVE ──────────────────────────
# Everything else (train-state, intermediate checkpoints, datasets, identity
# LoRAs) is deleted. Train-state can be re-generated by resuming training;
# training data lives in lora-data/ locally.
#
# Source of truth for what's live: `src/models/roles.ts` AGENT_MODELS +
# WRITER_GENRE_PACKS. To update this list, `grep wandb-artifact://` that
# file and add any new URI's collection name here.
KEEP_SERVING = {
    # adherence-events agent (roles.ts)
    ("adherence-checker-v4", None),  # None = keep ALL versions
    # retired v2 rollback slot — single version
    ("adherence-checker-v2-sft-resume", "v9"),
    # chapter-plan-checker agent (roles.ts)
    ("chapter-plan-checker-v2", None),
    ("chapter-plan-checker-v2-sft-resume", None),
    # continuity-facts / continuity-state agents (roles.ts)
    ("continuity-v2", None),
    ("continuity-v2-sft-resume", None),
    # tonal-pass agent (roles.ts, on-demand only)
    ("howard-tonal-v4-sft-resume", "v8"),
    # halluc-ungrounded agent (wired 2026-04-18, docs/archive/2026-04/hallucination-v3-wire-in-plan.md)
    ("halluc-ungrounded-v2", None),
    ("halluc-ungrounded-v2-sft-resume", None),
    # halluc-leak-salvatore agent (wired 2026-04-18, same plan)
    ("halluc-leak-salvatore-v1", None),
    ("halluc-leak-salvatore-v1-sft-resume", None),
    # Salvatore fantasy voice LoRA (WRITER_GENRE_PACKS salvatore-fantasy)
    ("salvatore-1988-v4", None),
    ("salvatore-1988-v4-sft-resume", None),
    # Salvatore v3 — retained as comparator for salvatore-distinctness-v1
    # eval (docs/evals/salvatore-distinctness-v1.md baseline ladder)
    ("salvatore-1988-v3", None),
    ("salvatore-1988-v3-sft-resume", None),
}


def should_keep(collection_name: str, version_name: str) -> tuple[bool, str]:
    """Return (keep, reason) for a specific artifact version."""
    version_tag = version_name.split(":")[-1] if ":" in version_name else None

    for keep_name, keep_ver in KEEP_SERVING:
        if collection_name == keep_name:
            if keep_ver is None:
                return True, "KEEP (serving — all versions)"
            if version_tag == keep_ver:
                return True, f"KEEP (serving: {keep_name}:{keep_ver})"

    return False, "DELETE"


def fmt_bytes(n: int) -> str:
    if n < 1024:
        return f"{n} B"
    if n < 1024 * 1024:
        return f"{n / 1024:.1f} KB"
    if n < 1024 * 1024 * 1024:
        return f"{n / (1024 * 1024):.1f} MB"
    return f"{n / (1024 * 1024 * 1024):.2f} GB"


def main():
    do_delete = "--delete" in sys.argv
    api = wandb.Api()

    total_keep = 0
    total_delete = 0
    delete_targets = []

    print(f"{'=' * 70}")
    print(f"W&B Storage Audit — {ENTITY}/{PROJECT}")
    print(f"Mode: {'DELETE' if do_delete else 'DRY RUN'}")
    print(f"{'=' * 70}\n")

    for atype in api.artifact_types(f"{ENTITY}/{PROJECT}"):
        for coll in atype.collections():
            try:
                versions = list(coll.artifacts())
            except Exception:
                continue

            if not versions:
                continue

            print(f"Collection: {coll.name}  (type: {atype.name})")

            for v in versions:
                aliases = list(v.aliases) if v.aliases else []
                size = v.size or 0

                keep, reason = should_keep(coll.name, v.name)

                marker = "  K" if keep else "  X"
                print(
                    f"{marker} {v.name:55s}  "
                    f"{fmt_bytes(size):>10s}  "
                    f"aliases={aliases}  "
                    f"{reason}"
                )

                if keep:
                    total_keep += size
                else:
                    total_delete += size
                    delete_targets.append(v)

            print()

    # ── Summary ──────────────────────────────────────────────────────────
    print(f"{'=' * 70}")
    print("SUMMARY")
    print(f"{'=' * 70}")
    print(f"  Keep on W&B:     {fmt_bytes(total_keep)}")
    print(f"  Delete from W&B: {fmt_bytes(total_delete)}  ({len(delete_targets)} artifacts)")
    print(f"  Total scanned:   {fmt_bytes(total_keep + total_delete)}")
    print()
    print(f"  After cleanup:   ~{fmt_bytes(total_keep)}")
    headroom = 5 * 1024**3 - total_keep
    print(f"  Free tier left:  ~{fmt_bytes(max(0, headroom))}")
    print()

    if not delete_targets:
        print("Nothing to delete — storage is already minimal.")
        return

    if not do_delete:
        print("Run with --delete to purge the marked artifacts.")
        return

    # ── Execute deletions ────────────────────────────────────────────────
    # W&B requires aliases to be stripped before an artifact can be deleted.
    # ART auto-assigns aliases (latest, step0, step1, sft-resume-*) that
    # block deletion with HTTP 409 if not removed first.
    print(f"Deleting {len(delete_targets)} artifact versions...\n")
    deleted = 0
    failed = 0
    for v in delete_targets:
        try:
            # Strip aliases first (required for ART-managed artifacts)
            if v.aliases:
                v.aliases = []
                v.save()
            print(f"  Deleting {v.name} ...", end=" ", flush=True)
            v.delete()
            print("done")
            deleted += 1
        except Exception as e:
            print(f"FAILED: {e}")
            failed += 1

    print(f"\nDeleted {deleted} artifacts. Failed: {failed}. Freed ~{fmt_bytes(total_delete)}.")
    print(f"W&B storage now ~{fmt_bytes(total_keep)}.")


if __name__ == "__main__":
    main()
