// Backward compatibility — re-export prompts from agent directories
export { prompt as WORLD_BUILDER_PROMPT } from "./agents/world-builder"
export { prompt as CHARACTER_AGENT_PROMPT } from "./agents/character-agent"
export { prompt as PLOTTER_AGENT_PROMPT } from "./agents/plotter"
export { prompt as PLANNING_PLOTTER_PROMPT } from "./agents/planning-plotter"
export { prompt as WRITER_AGENT_PROMPT } from "./agents/writer"
export { prompt as CONTINUITY_AGENT_PROMPT } from "./agents/continuity"
export { prompt as SUMMARY_EXTRACTOR_PROMPT } from "./agents/summary-extractor"
export { prompt as FACT_EXTRACTOR_PROMPT } from "./agents/fact-extractor"
export { prompt as CHARACTER_STATE_PROMPT } from "./agents/character-state"
export { prompt as CROSS_CHAPTER_CONTINUITY_PROMPT } from "./agents/cross-chapter-continuity"
export { prompt as PROSE_QUALITY_PROMPT } from "./agents/prose-quality"
export { prompt as REWRITER_AGENT_PROMPT } from "./agents/rewriter"
export { prompt as RELATIONSHIP_TIMELINE_PROMPT } from "./agents/relationship-timeline"
